#ifndef DATASTATISTICS_GLOBAL_H
#define DATASTATISTICS_GLOBAL_H

#include <QtCore/qglobal.h>


#if defined(DATASTATISTICS_LIBRARY)
#  define DATASTATISTICSSHARED_EXPORT Q_DECL_EXPORT
#elif DATASTATISTICS_LIBRARY_IMPORT
#  define DATASTATISTICSSHARED_EXPORT Q_DECL_IMPORT
#else
#  define DATASTATISTICSSHARED_EXPORT
#endif


#endif // DATASTATISTICS_GLOBAL_H
